# Taps
tap "heroku/brew"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask"

# Brews
brew 'bash'
brew 'git'
brew 'go'
brew 'node'
brew 'openssl'
brew 'postgresql'
brew 'python'
brew 'python3'
brew 'tree'
brew 'yarn'
brew 'zsh'
brew 'zsh-completions'

# Casks
cask 'atom'
cask 'docker'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
cask 'java'
cask 'mute-me' # microphone toggle for touch bar
cask 'postico' # pgadmin alternative
cask 'postman' # rest api ui
cask 'slack'
cask 'steermouse' # Better than usb overdrive
cask 'spotify'
cask 'vagrant'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'
cask 'zoomus' # video conferencing

# App Store Apps
mas 'Xcode', id: 497799835
